//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LPAR = 2;
  public static final int RPAR = 3;
  public static final int LBRACE = 4;
  public static final int RBRACE = 5;
  public static final int COMMA = 6;
  public static final int COLON = 7;
  public static final int SEMI = 8;
  public static final int OR = 9;
  public static final int ARROW = 10;
  public static final int EQ = 11;
  public static final int LT = 12;
  public static final int GT = 13;
  public static final int LT_SLASH = 14;
  public static final int TRANSICIONES = 15;
  public static final int NOMBRE = 16;
  public static final int KAFD = 17;
  public static final int KAP = 18;
  public static final int N = 19;
  public static final int T = 20;
  public static final int I = 21;
  public static final int A = 22;
  public static final int P = 23;
  public static final int VER = 24;
  public static final int DESC = 25;
  public static final int LAMBDA = 26;
  public static final int HASH = 27;
  public static final int ID = 28;
  public static final int STRING = 29;
  public static final int SYM = 30;
  public static final int ERROR = 31;
  
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "RPAR",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "COLON",
  "SEMI",
  "OR",
  "ARROW",
  "EQ",
  "LT",
  "GT",
  "LT_SLASH",
  "TRANSICIONES",
  "NOMBRE",
  "KAFD",
  "KAP",
  "N",
  "T",
  "I",
  "A",
  "P",
  "VER",
  "DESC",
  "LAMBDA",
  "HASH",
  "ID",
  "STRING",
  "SYM",
  "ERROR"
  };
}