
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMI = 6;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int DESC = 3;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RPAREN = 5;
  public static final int VER_AUTOMATAS = 2;
  public static final int LPAREN = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VER_AUTOMATAS",
  "DESC",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COMMA",
  "ID",
  "STRING"
  };
}

